pipeline {
    agent any

    stages {
        stage('Webhook Test') {
            steps {
                echo "Webhook triggered successfully!"
                sh 'date'
                sh 'git log -1 --oneline'
		#echo "Build #${env.BUILD_NUMBER}"
		sh 'echo "Webhook test at $(date)"'
            }
        }
    }
}
