name: AI Application Failure Analysis

on:
  workflow_dispatch:

jobs:
  analyze-failure:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name dev-eks-cluster

      - name: Collect Kubernetes Failure Diagnostics
        run: |
          cd Projects/CI-CD/GitHub-Actions/AI/AI_App_Failure_Analysis
          chmod +x scripts/collect_failure_data.sh
          ./scripts/collect_failure_data.sh
          cat failure-data.txt
      - name: Generate AI Prompt
        run: |
          cd Projects/CI-CD/GitHub-Actions/AI/AI_App_Failure_Analysis

          cp prompts/prompt.md final-prompt.txt

          echo "" >> final-prompt.txt
          echo "======================================================" >> final-prompt.txt
          echo "KUBERNETES DIAGNOSTICS" >> final-prompt.txt
          echo "======================================================" >> final-prompt.txt
          echo "" >> final-prompt.txt

          cat failure-data.txt >> final-prompt.txt
      - name: Display AI Prompt
        run: |
          cd Projects/CI-CD/GitHub-Actions/AI/AI_App_Failure_Analysis
          cat final-prompt.txt

      - name: Upload Diagnostics
        uses: actions/upload-artifact@v4
        with:
           name: kubernetes-failure-diagnostics
           path: |
              Projects/CI-CD/GitHub-Actions/AI/AI_App_Failure_Analysis/failure-data.txt
              Projects/CI-CD/GitHub-Actions/AI/AI_App_Failure_Analysis/final-prompt.txt