name: AI Application Failure Analysis

on:
  workflow_dispatch:

jobs:
  analyze-failure:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name dev-eks-cluster

      - name: Collect Kubernetes Failure Diagnostics
        run: |
         cd Projects/CI-CD/GitHub-Actions/AI/AI_App_Failure_Analysis
         chmod +x scripts/collect_failure_data.sh
         ./scripts/collect_failure_data.sh
         cat failure-data.txt
    #   - name: Display Diagnostics
    #     run: |
    #       cat failure-data.txt