name: AWS OIDC Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  aws-identity-test:
    runs-on: ubuntu-latest

    # defaults: 
    #   run:
    #     working-directory: Projects/CI-CD/GitHub-Actions

    steps:

      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::449957914366:role/GitHubActionsOIDCTestRole
          aws-region: us-east-1

      - name: Verify AWS identity
        run: aws sts get-caller-identity

 #### Create the AWS OIDC provider and IAM role  
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform version
        run: terraform version

    #   - name: Debug repository structure
    #     run: |
    #       echo "Current directory:"
    #       pwd

    #       echo ""
    #       echo "Top-level files/directories:"
    #       ls -la

    #       echo ""
    #       echo "Looking for main.tf:"
    #       find . -name main.tf -print


      - name: Terraform Init
        run: terraform -chdir=Projects/CI-CD/GitHub-Actions/terraform-oidc-test init


      - name: Terraform Format Check
        run: terraform -chdir=Projects/CI-CD/GitHub-Actions/terraform-oidc-test fmt -check


      # - name: Terraform AWS identity Init
      #   run: terraform -chdir=Projects/CI-CD/GitHub-Actions/terraform-oidc-test init

      - name: Terraform Validate
        run: terraform -chdir=Projects/CI-CD/GitHub-Actions/terraform-oidc-test validate

      # - name: Terraform Security Scan
      #   uses: aquasecurity/tfsec-action@v1.0.3
      #   with:
      #     working_directory: Projects/CI-CD/GitHub-Actions/terraform-oidc-test
  
      - name: Terraform Plan
        run: terraform -chdir=Projects/CI-CD/GitHub-Actions/terraform-oidc-test plan
 
 


